testCLCD

diff --git a/.github/workflows/CI-CD_Pipeline.yml b/.github/workflows/CI-CD_Pipeline.yml
--- a/.github/workflows/CI-CD_Pipeline.yml
+++ b/.github/workflows/CI-CD_Pipeline.yml
@@ -152,7 +152,13 @@ jobs:
             --query 'Instances[0].InstanceId' \
             --output text)
 
+          if [ -z "$INSTANCE_ID" ]; then
+            echo "Failed to create EC2 instance" >&2
+          exit 1
+          fi
+
           echo "Instance ID: $INSTANCE_ID"
+          
 
           # Wait for the instance to be running
           aws ec2 wait instance-running --instance-ids $INSTANCE_ID
